"""added funding and funding application models

Revision ID: 16250c140720
Revises: a48a087e8f52
Create Date: 2024-08-11 03:55:51.160542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16250c140720'
down_revision = 'a48a087e8f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('grant_name', sa.String(length=120), nullable=False),
    sa.Column('grant_type', sa.Enum('SOCIAL_AID', 'BUSINESS', name='granttype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('funding_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'IN_REVIEW', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('application_type', sa.Enum('SOCIAL_AID', 'BUSINESS', name='applicationtype'), nullable=False),
    sa.Column('supporting_documents', sa.Text(), nullable=True),
    sa.Column('household_income', sa.Integer(), nullable=True),
    sa.Column('number_of_dependents', sa.Integer(), nullable=True),
    sa.Column('reason_for_aid', sa.Text(), nullable=True),
    sa.Column('concept_note', sa.Text(), nullable=True),
    sa.Column('business_profile', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['funding_id'], ['funding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_application')
    op.drop_table('funding')
    # ### end Alembic commands ###
